create_expense:
  name: Create expense
  description: Create an expense in a Spliit group.
  fields:
    config_entry_id:
      name: Config Entry ID
      description: Optional: choose a specific Spliit config entry (use if you have multiple).
      required: false
    title:
      name: Title
      description: Expense title.
      required: true
      example: "Groceries"
    amount:
      name: Amount (in cents)
      description: Total amount in the smallest currency unit (e.g., cents).
      required: true
      example: 1299
      selector:
        number:
          min: 1
          mode: box
          step: 1
    paid_by:
      name: Paid by (name or user id)
      description: Display name (resolved to ID) or a direct Spliit user id.
      required: true
      example: "Alice"
    paid_for:
      name: Paid for (list of 'name_or_id:value' pairs)
      description: >
        When split_mode is BY_PERCENTAGE, values are percents (sum to 100).
        When BY_AMOUNT, values are in cents (sum to total).
        When BY_SHARES, values are share units (positive integers).
        If omitted with split_mode EVENLY (default), the integration splits among all group participants.
      required: false
      example:
        - "Alice:60"
        - "Bob:40"
    split_mode:
      name: Split mode
      description: EVENLY (default), BY_PERCENTAGE, BY_AMOUNT, or BY_SHARES.
      required: false
      example: "BY_AMOUNT"
      selector:
        select:
          options:
            - EVENLY
            - BY_PERCENTAGE
            - BY_AMOUNT
            - BY_SHARES
    note:
      name: Note
      description: Optional note for the expense.
      required: false
